/**
 * WP-Places' own test ids (CONTRACTS §1 rule 8). Import-free, so e2e specs can
 * import it by relative path. Never rename an id.
 */
export const PLACES_TESTID = {
	// palette
	paletteInput: "places-palette-input",
	paletteResult: "places-result",
	paletteTripResult: "places-trip-result",
	paletteTripLeg: "places-trip-leg",
	previewCard: "places-preview",
	filingChip: "places-filing",
	categoryChips: "places-categories",
	saveToIdeas: "places-save-ideas",
	schedule: "places-schedule",
	scheduleMenu: "places-schedule-menu",
	useLocation: "places-use-location",
	dropPin: "places-drop-pin",
	dropPinUse: "places-drop-pin-use",
	providerFooter: "places-provider-footer",
	paletteEmpty: "places-palette-empty",
	coordsResult: "places-coords-result",
	coordsError: "places-coords-error",
	pinAddress: "places-pin-address",
	paletteRate: "places-palette-rate",
	// node overview
	priorityRow: "places-priority-row",
	priorityPicker: "places-priority-picker",
	ratingComment: "places-rating-comment",
	ratingCommentCount: "places-rating-comment-count",
	description: "places-description",
	refile: "places-refile",
	occurrence: "places-occurrence",
	visits: "places-visits",
	children: "places-children",
	zoomIn: "places-zoom-in",
	moreDetails: "places-more-details",
	openInMaps: "places-open-in-maps",
	setLocation: "places-set-location",
	rateLink: "places-rate-link",
	tzPicker: "places-tz-picker",
	/** FB-20: the zone's offset over the trip's dates ("GMT-4 → GMT-5 from Nov 7"). */
	tzOffsets: "places-tz-offsets",
	/** "Now 14:05 EDT" (FB-20: the only label that reads the current time). */
	localTimeNow: "places-local-time-now",
	// days per city
	daysTable: "places-days-table",
	daysRow: "places-days-row",
	daysInput: "places-days-input",
	daysUnallocated: "places-days-unallocated",
	plannedDays: "places-planned-days",
	// rate screen
	rateScreen: "rate-screen",
	/** The "Ideas ×" chip: the screen holds the Ideas list's places (FB-05). */
	rateIdeasSet: "rate-ideas-set",
	rateBack: "rate-back",
	rateCard: "rate-card",
	rateButton: "rate-button",
	rateComment: "rate-comment",
	rateCommentSave: "rate-comment-save",
	rateNext: "rate-next",
	ratePrev: "rate-prev",
	rateProgress: "rate-progress",
	rateView: "rate-view",
	rateTable: "rate-table",
	rateTableRow: "rate-table-row",
	rateCompare: "rate-compare",
	rateCompareRow: "rate-compare-row",
	rateFilter: "rate-filter",
	rateSchedule: "rate-schedule",
	rateIdeas: "rate-ideas",
	rateMedia: "rate-media",
	rateMediaFrom: "rate-media-from",
	feedMedia: "rate-feed-media",
	rateMediaBars: "rate-media-bars",
	rateMediaEmpty: "rate-media-empty",
	rateAddPhoto: "rate-add-photo",
	rateAddPhotoInput: "rate-add-photo-input",
	rateAddLink: "rate-add-link",
	rateAddLinkInput: "rate-add-link-input",
	rateLinks: "rate-links",
	rateMiniMap: "rate-minimap",
	rateEmpty: "rate-empty",
	ratePdf: "rate-pdf",
} as const;
