/**
 * WP-Money's own `data-testid`s (CONTRACTS §1 rule 8). Import-free, so e2e
 * specs can import this file by relative path. Never rename an id.
 */
export const MONEY_TESTID = {
	summary: "money-summary",
	summaryPlanned: "money-summary-planned",
	summaryActual: "money-summary-actual",
	summaryRemaining: "money-summary-remaining",
	summaryMyShare: "money-summary-my-share",
	people: "money-people",
	personRow: "money-person-row",
	netPositions: "money-net-positions",
	balances: "money-balances",
	balanceNotice: "money-balance-notice",
	settleUpButton: "money-settle-up",
	settleUpDialog: "money-settle-up-dialog",
	transferRow: "money-transfer-row",
	transferRecord: "money-transfer-record",
	settlementRow: "money-settlement-row",
	settlementTag: "money-settlement-tag",
	budget: "money-budget",
	budgetRow: "money-budget-row",
	budgetEdit: "money-budget-edit",
	budgetNotice: "money-budget-notice",
	budgetPrivate: "money-budget-private",
	breakdown: "money-breakdown",
	expenseList: "money-expense-list",
	expenseRow: "money-expense-row",
	shoppingRow: "money-shopping-row",
	addButton: "money-add",
	displayCurrency: "money-display-currency",
	moreMenu: "money-more",
	exportCsv: "money-export-csv",
	// The expense editor
	amount: "expense-amount",
	currency: "expense-currency",
	title: "expense-title",
	status: "expense-status",
	payer: "expense-payer",
	splitToggle: "expense-split-toggle",
	splitPerson: "expense-split-person",
	splitExact: "expense-split-exact",
	splitExactAmount: "expense-split-exact-amount",
	splitAddPerson: "expense-split-add-person",
	more: "expense-more",
	category: "expense-category",
	private: "expense-private",
	itemize: "expense-itemize",
	line: "expense-line",
	lineLabel: "expense-line-label",
	lineAmount: "expense-line-amount",
	linePerson: "expense-line-person",
	addLine: "expense-add-line",
	addFee: "expense-add-fee",
	feeValue: "expense-fee-value",
	remainder: "expense-remainder",
	problems: "expense-problems",
	points: "expense-points",
	payments: "expense-payments",
	paymentRow: "expense-payment-row",
	markPaid: "expense-mark-paid",
	addPayment: "expense-add-payment",
	multiPayer: "expense-multi-payer",
	payerAmount: "expense-payer-amount",
	paymentCurrency: "expense-payment-currency",
	paymentPayerAmount: "expense-payment-payer-amount",
	paymentAddPayer: "expense-payment-add-payer",
	paymentRate: "expense-payment-rate",
	paymentRateSource: "expense-payment-rate-source",
	refund: "expense-refund",
	receipt: "expense-receipt",
	receipts: "expense-receipts",
	save: "expense-save",
	delete: "expense-delete",
	converted: "expense-converted",
} as const;
