/**
 * WP-Insights' own `data-testid`s (CONTRACTS §1 rule 8). Import-free, so e2e
 * specs can import it by relative path. The public component ids
 * (`hours-chip`, `shift-trip-dialog`, …) stay in `@/lib/testids`.
 */
export const INSIGHTS_TESTID = {
	// E1 hours
	hoursPopover: "hours-popover",
	hoursIssueRow: "hours-issue-row",
	hoursFix: "hours-fix",
	hoursEditHours: "hours-edit-hours",
	hoursSource: "hours-source",
	dayHoursRow: "day-hours-row",
	hoursFetch: "hours-fetch",
	hoursTableRow: "hours-table-row",
	hoursRules: "hours-rules",
	hoursTableEdit: "hours-table-edit",
	hoursTableConfirm: "hours-table-confirm",
	hoursTableAdd: "hours-table-add",
	hoursSuggested: "hours-suggested",
	hoursSuggestedChange: "hours-suggested-change",
	hoursEditorBanner: "hours-editor-banner",
	hoursEditorMode: "hours-editor-mode",
	hoursEditorDay: "hours-editor-day",
	hoursEditorDayState: "hours-editor-day-state",
	hoursEditorOpen: "hours-editor-open",
	hoursEditorClose: "hours-editor-close",
	hoursEditorAddRange: "hours-editor-add-range",
	hoursEditorCopyMon: "hours-editor-copy-mon",
	hoursEditorHoliday: "hours-editor-holiday",
	hoursEditorNth: "hours-editor-nth",
	hoursEditorAddNth: "hours-editor-add-nth",
	hoursEditorLastEntry: "hours-editor-last-entry",
	hoursEditorClosedDay: "hours-editor-closed-day",
	hoursEditorException: "hours-editor-exception",
	hoursEditorAddException: "hours-editor-add-exception",
	hoursEditorNote: "hours-editor-note",
	hoursEditorSave: "hours-editor-save",
	hoursEditorRemove: "hours-editor-remove",
	hoursEditorError: "hours-editor-error",
	holidayRow: "holiday-row",
	holidayAdd: "holiday-add",
	holidaySave: "holiday-save",
	// E2 what-if
	shiftMinus: "shift-minus",
	shiftPlus: "shift-plus",
	shiftDelta: "shift-delta",
	shiftDay1: "shift-day1",
	shiftSummary: "shift-summary",
	shiftApply: "shift-apply",
	shiftDiscard: "shift-discard",
	shiftConflict: "shift-conflict",
	impactSection: "impact-section",
	impactRow: "impact-row",
	markBooked: "mark-booked",
	whatIfReview: "what-if-review",
	whatIfClear: "what-if-clear",
	// E3 sun + climate
	daySunDetail: "day-sun-detail",
	climateLine: "climate-line",
	climateRow: "climate-row",
	climateCaption: "climate-caption",
	climateUnavailable: "climate-unavailable",
} as const;
