/**
 * English names for N02 lines and operators (N02 is Japanese-only; QA MT-06:
 * "高尾線", "南武線" chips). Lines whose timing is tuned carry their name in
 * `LINE_OVERRIDES` (profiles.server.ts); this table names the rest of the
 * Kanto, Fuji, Chubu and Kansai networks and every JR line, so chips, labels
 * and custom-route steps read in English. Keys are `${operator}|${line}` as in
 * N02 (`lineKey`). A line missing here keeps its Japanese name.
 */

export const LINE_NAMES_EN: Readonly<Record<string, string>> = {
	// ── Kanto: JR East ───────────────────────────────────────────────────────
	"東日本旅客鉄道|両毛線": "JR Ryomo Line",
	"東日本旅客鉄道|久留里線": "JR Kururi Line",
	"東日本旅客鉄道|五日市線": "JR Itsukaichi Line",
	"東日本旅客鉄道|京葉線": "JR Keiyo Line",
	"東日本旅客鉄道|伊東線": "JR Ito Line",
	"東日本旅客鉄道|八高線": "JR Hachiko Line",
	"東日本旅客鉄道|内房線": "JR Uchibo Line",
	"東日本旅客鉄道|南武線": "JR Nambu Line",
	"東日本旅客鉄道|吾妻線": "JR Agatsuma Line",
	"東日本旅客鉄道|外房線": "JR Sotobo Line",
	"東日本旅客鉄道|小海線": "JR Koumi Line",
	"東日本旅客鉄道|川越線": "JR Kawagoe Line",
	"東日本旅客鉄道|成田線": "JR Narita Line",
	"東日本旅客鉄道|東金線": "JR Togane Line",
	"東日本旅客鉄道|根岸線": "JR Negishi Line",
	"東日本旅客鉄道|横浜線": "JR Yokohama Line",
	"東日本旅客鉄道|横須賀線": "JR Yokosuka Line",
	"東日本旅客鉄道|武蔵野線": "JR Musashino Line",
	"東日本旅客鉄道|水戸線": "JR Mito Line",
	"東日本旅客鉄道|相模線": "JR Sagami Line",
	"東日本旅客鉄道|赤羽線": "JR Saikyo Line (Akabane)",
	"東日本旅客鉄道|青梅線": "JR Ome Line",
	"東日本旅客鉄道|高崎線": "JR Takasaki Line",
	"東日本旅客鉄道|鶴見線": "JR Tsurumi Line",
	"東日本旅客鉄道|鹿島線": "JR Kashima Line",
	"東日本旅客鉄道|常磐線": "JR Joban Line",
	"東日本旅客鉄道|日光線": "JR Nikko Line",
	"東日本旅客鉄道|烏山線": "JR Karasuyama Line",
	"東日本旅客鉄道|水郡線": "JR Suigun Line",
	"東日本旅客鉄道|上越線": "JR Joetsu Line",
	"東日本旅客鉄道|信越線": "JR Shin'etsu Line",
	"東日本旅客鉄道|篠ノ井線": "JR Shinonoi Line",
	"東日本旅客鉄道|大糸線": "JR Oito Line",
	"東日本旅客鉄道|飯山線": "JR Iiyama Line",
	"東日本旅客鉄道|弥彦線": "JR Yahiko Line",
	"東日本旅客鉄道|越後線": "JR Echigo Line",
	"東日本旅客鉄道|白新線": "JR Hakushin Line",
	"東日本旅客鉄道|羽越線": "JR Uetsu Line",
	"東日本旅客鉄道|米坂線": "JR Yonesaka Line",
	"東日本旅客鉄道|只見線": "JR Tadami Line",
	"東日本旅客鉄道|磐越東線": "JR Ban'etsu East Line",
	"東日本旅客鉄道|磐越西線": "JR Ban'etsu West Line",
	"東日本旅客鉄道|仙山線": "JR Senzan Line",
	"東日本旅客鉄道|仙石線": "JR Senseki Line",
	"東日本旅客鉄道|石巻線": "JR Ishinomaki Line",
	"東日本旅客鉄道|気仙沼線": "JR Kesennuma Line",
	"東日本旅客鉄道|大船渡線": "JR Ofunato Line",
	"東日本旅客鉄道|北上線": "JR Kitakami Line",
	"東日本旅客鉄道|釜石線": "JR Kamaishi Line",
	"東日本旅客鉄道|山田線": "JR Yamada Line",
	"東日本旅客鉄道|八戸線": "JR Hachinohe Line",
	"東日本旅客鉄道|大湊線": "JR Ominato Line",
	"東日本旅客鉄道|津軽線": "JR Tsugaru Line",
	"東日本旅客鉄道|五能線": "JR Gono Line",
	"東日本旅客鉄道|奥羽線": "JR Ou Line",
	"東日本旅客鉄道|男鹿線": "JR Oga Line",
	"東日本旅客鉄道|田沢湖線": "JR Tazawako Line",
	"東日本旅客鉄道|花輪線": "JR Hanawa Line",
	"東日本旅客鉄道|左沢線": "JR Aterazawa Line",
	"東日本旅客鉄道|陸羽東線": "JR Rikuu East Line",
	"東日本旅客鉄道|陸羽西線": "JR Rikuu West Line",
	// ── JR Central ───────────────────────────────────────────────────────────
	"東海旅客鉄道|御殿場線": "JR Gotemba Line",
	"東海旅客鉄道|太多線": "JR Taita Line",
	"東海旅客鉄道|武豊線": "JR Taketoyo Line",
	"東海旅客鉄道|関西線": "JR Kansai Line",
	"東海旅客鉄道|参宮線": "JR Sangu Line",
	"東海旅客鉄道|名松線": "JR Meisho Line",
	"東海旅客鉄道|紀勢線": "JR Kisei Line",
	"東海旅客鉄道|飯田線": "JR Iida Line",
	"東海旅客鉄道|高山線": "JR Takayama Line",
	"JR東海交通事業|城北線": "Johoku Line",
	// ── JR West ──────────────────────────────────────────────────────────────
	"西日本旅客鉄道|JR東西線": "JR Tozai Line",
	"西日本旅客鉄道|おおさか東線": "JR Osaka Higashi Line",
	"西日本旅客鉄道|加古川線": "JR Kakogawa Line",
	"西日本旅客鉄道|和歌山線": "JR Wakayama Line",
	"西日本旅客鉄道|桜井線": "JR Man'yo-Mahoroba Line (Sakurai)",
	"西日本旅客鉄道|桜島線": "JR Yumesaki Line (Sakurajima)",
	"西日本旅客鉄道|湖西線": "JR Kosei Line",
	"西日本旅客鉄道|片町線": "JR Gakkentoshi Line (Katamachi)",
	"西日本旅客鉄道|福知山線": "JR Takarazuka Line (Fukuchiyama)",
	"西日本旅客鉄道|草津線": "JR Kusatsu Line",
	"西日本旅客鉄道|七尾線": "JR Nanao Line",
	"西日本旅客鉄道|伯備線": "JR Hakubi Line",
	"西日本旅客鉄道|北陸線": "JR Hokuriku Line",
	"西日本旅客鉄道|博多南線": "JR Hakata-Minami Line",
	"西日本旅客鉄道|可部線": "JR Kabe Line",
	"西日本旅客鉄道|吉備線": "JR Kibi Line",
	"西日本旅客鉄道|呉線": "JR Kure Line",
	"西日本旅客鉄道|因美線": "JR Inbi Line",
	"西日本旅客鉄道|城端線": "JR Johana Line",
	"西日本旅客鉄道|境線": "JR Sakai Line",
	"西日本旅客鉄道|大糸線": "JR Oito Line",
	"西日本旅客鉄道|姫新線": "JR Kishin Line",
	"西日本旅客鉄道|宇部線": "JR Ube Line",
	"西日本旅客鉄道|宇野線": "JR Uno Line",
	"西日本旅客鉄道|小浜線": "JR Obama Line",
	"西日本旅客鉄道|小野田線": "JR Onoda Line",
	"西日本旅客鉄道|山口線": "JR Yamaguchi Line",
	"西日本旅客鉄道|山陽線": "JR Sanyo Line",
	"西日本旅客鉄道|岩徳線": "JR Gantoku Line",
	"西日本旅客鉄道|播但線": "JR Bantan Line",
	"西日本旅客鉄道|木次線": "JR Kisuki Line",
	"西日本旅客鉄道|本四備讃線": "JR Seto-Ohashi Line",
	"西日本旅客鉄道|氷見線": "JR Himi Line",
	"西日本旅客鉄道|津山線": "JR Tsuyama Line",
	"西日本旅客鉄道|福塩線": "JR Fukuen Line",
	"西日本旅客鉄道|紀勢線": "JR Kisei Line",
	"西日本旅客鉄道|美祢線": "JR Mine Line",
	"西日本旅客鉄道|舞鶴線": "JR Maizuru Line",
	"西日本旅客鉄道|芸備線": "JR Geibi Line",
	"西日本旅客鉄道|赤穂線": "JR Ako Line",
	"西日本旅客鉄道|越美北線": "JR Etsumi-Hoku Line",
	"西日本旅客鉄道|高山線": "JR Takayama Line",
	// ── JR Hokkaido, Shikoku, Kyushu ─────────────────────────────────────────
	"北海道旅客鉄道|北海道新幹線": "Hokkaido Shinkansen",
	"北海道旅客鉄道|函館線": "JR Hakodate Line",
	"北海道旅客鉄道|千歳線": "JR Chitose Line",
	"北海道旅客鉄道|宗谷線": "JR Soya Line",
	"北海道旅客鉄道|室蘭線": "JR Muroran Line",
	"北海道旅客鉄道|富良野線": "JR Furano Line",
	"北海道旅客鉄道|日高線": "JR Hidaka Line",
	"北海道旅客鉄道|札沼線": "JR Sassho Line",
	"北海道旅客鉄道|根室線": "JR Nemuro Line",
	"北海道旅客鉄道|海峡線": "JR Kaikyo Line",
	"北海道旅客鉄道|留萌線": "JR Rumoi Line",
	"北海道旅客鉄道|石勝線": "JR Sekisho Line",
	"北海道旅客鉄道|石北線": "JR Sekihoku Line",
	"北海道旅客鉄道|釧網線": "JR Senmo Line",
	"四国旅客鉄道|予土線": "JR Yodo Line",
	"四国旅客鉄道|予讃線": "JR Yosan Line",
	"四国旅客鉄道|内子線": "JR Uchiko Line",
	"四国旅客鉄道|土讃線": "JR Dosan Line",
	"四国旅客鉄道|徳島線": "JR Tokushima Line",
	"四国旅客鉄道|本四備讃線": "JR Seto-Ohashi Line",
	"四国旅客鉄道|牟岐線": "JR Mugi Line",
	"四国旅客鉄道|高徳線": "JR Kotoku Line",
	"四国旅客鉄道|鳴門線": "JR Naruto Line",
	"九州旅客鉄道|西九州新幹線": "Nishi-Kyushu Shinkansen",
	"九州旅客鉄道|三角線": "JR Misumi Line",
	"九州旅客鉄道|久大線": "JR Kyudai Line",
	"九州旅客鉄道|佐世保線": "JR Sasebo Line",
	"九州旅客鉄道|吉都線": "JR Kitto Line",
	"九州旅客鉄道|唐津線": "JR Karatsu Line",
	"九州旅客鉄道|大村線": "JR Omura Line",
	"九州旅客鉄道|宮崎空港線": "JR Miyazaki Airport Line",
	"九州旅客鉄道|山陽線": "JR Sanyo Line",
	"九州旅客鉄道|後藤寺線": "JR Gotoji Line",
	"九州旅客鉄道|指宿枕崎線": "JR Ibusuki-Makurazaki Line",
	"九州旅客鉄道|日南線": "JR Nichinan Line",
	"九州旅客鉄道|日田彦山線": "JR Hitahikosan Line",
	"九州旅客鉄道|日豊線": "JR Nippo Line",
	"九州旅客鉄道|筑肥線": "JR Chikuhi Line",
	"九州旅客鉄道|筑豊線": "JR Chikuho Line",
	"九州旅客鉄道|篠栗線": "JR Sasaguri Line",
	"九州旅客鉄道|肥薩線": "JR Hisatsu Line",
	"九州旅客鉄道|豊肥線": "JR Hohi Line",
	"九州旅客鉄道|長崎線": "JR Nagasaki Line",
	"九州旅客鉄道|香椎線": "JR Kashii Line",
	"九州旅客鉄道|鹿児島線": "JR Kagoshima Line",
	// ── Tokyo: subways, trams, AGT, monorails ────────────────────────────────
	"東京地下鉄|4号線丸ノ内線分岐線":
		"Tokyo Metro Marunouchi Line (Honancho branch)",
	"東京都|日暮里・舎人ライナー": "Nippori-Toneri Liner",
	"東京都|荒川線": "Toden Arakawa Line",
	"ゆりかもめ|東京臨海新交通臨海線": "Yurikamome",
	"東京臨海高速鉄道|臨海副都心線": "Rinkai Line",
	"首都圏新都市鉄道|常磐新線": "Tsukuba Express",
	"多摩都市モノレール|多摩都市モノレール線": "Tama Monorail",
	"舞浜リゾートライン|ディズニーリゾートライン": "Disney Resort Line",
	"埼玉高速鉄道|埼玉高速鉄道線": "Saitama Railway Line",
	"埼玉新都市交通|伊奈線": "New Shuttle",
	"東葉高速鉄道|東葉高速線": "Toyo Rapid Line",
	"北総鉄道|北総線": "Hokuso Line",
	"芝山鉄道|芝山鉄道線": "Shibayama Railway Line",
	"千葉都市モノレール|1号線": "Chiba Monorail Line 1",
	"千葉都市モノレール|2号線": "Chiba Monorail Line 2",
	"山万|ユーカリが丘線": "Yukarigaoka Line",
	"流鉄|流山線": "Ryutetsu Nagareyama Line",
	// ── Tokyo: private railways ──────────────────────────────────────────────
	"京王電鉄|高尾線": "Keio Takao Line",
	"京王電鉄|相模原線": "Keio Sagamihara Line",
	"京王電鉄|動物園線": "Keio Dobutsuen Line",
	"京王電鉄|競馬場線": "Keio Keibajo Line",
	"小田急電鉄|多摩線": "Odakyu Tama Line",
	"小田急電鉄|江ノ島線": "Odakyu Enoshima Line",
	"小田急箱根|鉄道線": "Hakone Tozan Line",
	"小田急箱根|鋼索線": "Hakone Tozan Cable Car",
	"東急電鉄|東横線": "Tokyu Toyoko Line",
	"東急電鉄|田園都市線": "Tokyu Den-en-toshi Line",
	"東急電鉄|目黒線": "Tokyu Meguro Line",
	"東急電鉄|大井町線": "Tokyu Oimachi Line",
	"東急電鉄|池上線": "Tokyu Ikegami Line",
	"東急電鉄|東急多摩川線": "Tokyu Tamagawa Line",
	"東急電鉄|世田谷線": "Tokyu Setagaya Line",
	"東急電鉄|こどもの国線": "Tokyu Kodomonokuni Line",
	"東急電鉄|東急新横浜線": "Tokyu Shin-Yokohama Line",
	"西武鉄道|池袋線": "Seibu Ikebukuro Line",
	"西武鉄道|新宿線": "Seibu Shinjuku Line",
	"西武鉄道|西武秩父線": "Seibu Chichibu Line",
	"西武鉄道|西武有楽町線": "Seibu Yurakucho Line",
	"西武鉄道|拝島線": "Seibu Haijima Line",
	"西武鉄道|国分寺線": "Seibu Kokubunji Line",
	"西武鉄道|多摩川線": "Seibu Tamagawa Line",
	"西武鉄道|多摩湖線": "Seibu Tamako Line",
	"西武鉄道|狭山線": "Seibu Sayama Line",
	"西武鉄道|西武園線": "Seibu Seibuen Line",
	"西武鉄道|豊島線": "Seibu Toshima Line",
	"西武鉄道|山口線": "Seibu Yamaguchi Line",
	"東武鉄道|伊勢崎線": "Tobu Skytree Line (Isesaki)",
	"東武鉄道|日光線": "Tobu Nikko Line",
	"東武鉄道|東上本線": "Tobu Tojo Line",
	"東武鉄道|野田線": "Tobu Urban Park Line (Noda)",
	"東武鉄道|亀戸線": "Tobu Kameido Line",
	"東武鉄道|大師線": "Tobu Daishi Line",
	"東武鉄道|宇都宮線": "Tobu Utsunomiya Line",
	"東武鉄道|佐野線": "Tobu Sano Line",
	"東武鉄道|小泉線": "Tobu Koizumi Line",
	"東武鉄道|桐生線": "Tobu Kiryu Line",
	"東武鉄道|越生線": "Tobu Ogose Line",
	"京成電鉄|本線": "Keisei Main Line",
	"京成電鉄|押上線": "Keisei Oshiage Line",
	"京成電鉄|成田空港線": "Keisei Narita Sky Access",
	"京成電鉄|東成田線": "Keisei Higashi-Narita Line",
	"京成電鉄|千葉線": "Keisei Chiba Line",
	"京成電鉄|千原線": "Keisei Chihara Line",
	"京成電鉄|松戸線": "Keisei Matsudo Line",
	"京成電鉄|金町線": "Keisei Kanamachi Line",
	"京浜急行電鉄|久里浜線": "Keikyu Kurihama Line",
	"京浜急行電鉄|大師線": "Keikyu Daishi Line",
	"京浜急行電鉄|逗子線": "Keikyu Zushi Line",
	"相模鉄道|相鉄本線": "Sotetsu Main Line",
	"相模鉄道|相鉄いずみ野線": "Sotetsu Izumino Line",
	"相模鉄道|相鉄新横浜線": "Sotetsu Shin-Yokohama Line",
	"横浜市|1号線": "Yokohama Subway Blue Line",
	"横浜市|3号線": "Yokohama Subway Blue Line",
	"横浜市|4号線": "Yokohama Subway Green Line",
	"横浜高速鉄道|みなとみらい21線": "Minatomirai Line",
	"横浜シーサイドライン|金沢シーサイドライン": "Kanazawa Seaside Line",
	"江ノ島電鉄|江ノ島電鉄線": "Enoden (Enoshima Electric Railway)",
	"湘南モノレール|江の島線": "Shonan Monorail",
	"高尾登山電鉄|高尾鋼索線": "Mt. Takao Cable Car",
	"御岳登山鉄道|ケーブルカー": "Mitake Cable Car",
	"大山観光電鉄|大山鋼索線": "Oyama Cable Car",
	"十国峠|十国鋼索線": "Jukkoku Pass Cable Car",
	"筑波観光鉄道|筑波山鋼索鉄道線": "Mt. Tsukuba Cable Car",
	// ── Kanto and Izu: regional railways ─────────────────────────────────────
	"伊豆急行|伊豆急行線": "Izukyu Line",
	"伊豆箱根鉄道|駿豆線": "Izuhakone Sunzu Line",
	"伊豆箱根鉄道|大雄山線": "Izuhakone Daiyuzan Line",
	"岳南電車|岳南鉄道線": "Gakunan Railway Line",
	"静岡鉄道|静岡清水線": "Shizutetsu Shizuoka-Shimizu Line",
	"秩父鉄道|秩父本線": "Chichibu Railway Main Line",
	"関東鉄道|常総線": "Kanto Railway Joso Line",
	"関東鉄道|竜ヶ崎線": "Kanto Railway Ryugasaki Line",
	"鹿島臨海鉄道|大洗鹿島線": "Oarai-Kashima Line",
	"ひたちなか海浜鉄道|湊線": "Hitachinaka Minato Line",
	"真岡鐵道|真岡線": "Moka Line",
	"上毛電気鉄道|上毛線": "Jomo Line",
	"上信電鉄|上信線": "Joshin Line",
	"わたらせ渓谷鐵道|わたらせ渓谷線": "Watarase Keikoku Line",
	"いすみ鉄道|いすみ線": "Isumi Line",
	"小湊鐵道|小湊鐵道線": "Kominato Line",
	"銚子電気鉄道|銚子電気鉄道線": "Choshi Electric Railway",
	"宇都宮ライトレール|宇都宮芳賀ライトレール線": "Utsunomiya Light Rail",
	// ── Chubu: Nagoya ────────────────────────────────────────────────────────
	"名古屋市|2号線名港線": "Nagoya Subway Meiko Line",
	"名古屋市|上飯田線": "Nagoya Subway Kamiiida Line",
	"名古屋臨海高速鉄道|西名古屋港線": "Aonami Line",
	"名古屋ガイドウェイバス|ガイドウェイバス志段味線": "Yutorito Line",
	"名古屋鉄道|名古屋本線": "Meitetsu Nagoya Main Line",
	"名古屋鉄道|犬山線": "Meitetsu Inuyama Line",
	"名古屋鉄道|常滑線": "Meitetsu Tokoname Line",
	"名古屋鉄道|空港線": "Meitetsu Airport Line",
	"名古屋鉄道|河和線": "Meitetsu Kowa Line",
	"名古屋鉄道|知多新線": "Meitetsu Chita New Line",
	"名古屋鉄道|瀬戸線": "Meitetsu Seto Line",
	"名古屋鉄道|津島線": "Meitetsu Tsushima Line",
	"名古屋鉄道|尾西線": "Meitetsu Bisai Line",
	"名古屋鉄道|三河線": "Meitetsu Mikawa Line",
	"名古屋鉄道|各務原線": "Meitetsu Kakamigahara Line",
	"名古屋鉄道|小牧線": "Meitetsu Komaki Line",
	"名古屋鉄道|広見線": "Meitetsu Hiromi Line",
	"名古屋鉄道|竹鼻線": "Meitetsu Takehana Line",
	"名古屋鉄道|羽島線": "Meitetsu Hashima Line",
	"名古屋鉄道|築港線": "Meitetsu Chikko Line",
	"名古屋鉄道|蒲郡線": "Meitetsu Gamagori Line",
	"名古屋鉄道|西尾線": "Meitetsu Nishio Line",
	"名古屋鉄道|豊川線": "Meitetsu Toyokawa Line",
	"名古屋鉄道|豊田線": "Meitetsu Toyota Line",
	"愛知環状鉄道|愛知環状鉄道線": "Aichi Loop Line",
	"近畿日本鉄道|名古屋線": "Kintetsu Nagoya Line",
	"近畿日本鉄道|湯の山線": "Kintetsu Yunoyama Line",
	"近畿日本鉄道|鈴鹿線": "Kintetsu Suzuka Line",
	"三岐鉄道|三岐線": "Sangi Line",
	"三岐鉄道|北勢線": "Sangi Hokusei Line",
	"三岐鉄道|近鉄連絡線": "Sangi Kintetsu Connecting Line",
	"伊勢鉄道|伊勢線": "Ise Railway Line",
	"四日市あすなろう鉄道|内部線": "Asunarou Utsube Line",
	"四日市あすなろう鉄道|八王子線": "Asunarou Hachioji Line",
	"養老鉄道|養老線": "Yoro Line",
	"樽見鉄道|樽見線": "Tarumi Line",
	"明知鉄道|明知線": "Akechi Line",
	"豊橋鉄道|渥美線": "Toyotetsu Atsumi Line",
	"豊橋鉄道|東田本線": "Toyotetsu Azumada Line",
	// ── Kansai: Kyoto ────────────────────────────────────────────────────────
	"叡山電鉄|叡山本線": "Eizan Main Line",
	"叡山電鉄|鞍馬線": "Eizan Kurama Line",
	"京福電気鉄道|鋼索線": "Eizan Cable Car",
	"比叡山鉄道|比叡山鉄道線": "Sakamoto Cable Car",
	"鞍馬寺|鞍馬山鋼索鉄道": "Kurama-dera Cable Car",
	"嵯峨野観光鉄道|嵯峨野観光線": "Sagano Scenic Railway",
	"京阪電気鉄道|京津線": "Keihan Keishin Line",
	"京阪電気鉄道|石山坂本線": "Keihan Ishiyama-Sakamoto Line",
	"京阪電気鉄道|中之島線": "Keihan Nakanoshima Line",
	"京阪電気鉄道|交野線": "Keihan Katano Line",
	"京阪電気鉄道|鋼索線": "Iwashimizu-Hachimangu Cable Car",
	"近江鉄道|本線": "Ohmi Railway Main Line",
	"近江鉄道|八日市線": "Ohmi Railway Yokaichi Line",
	"近江鉄道|多賀線": "Ohmi Railway Taga Line",
	"信楽高原鐵道|信楽線": "Shigaraki Line",
	// ── Kansai: Osaka, Nara, Wakayama ────────────────────────────────────────
	"大阪市高速電気軌道|南港ポートタウン線": "Osaka Metro New Tram",
	"北大阪急行電鉄|南北線": "Kita-Osaka Kyuko Line",
	"大阪モノレール|大阪モノレール線": "Osaka Monorail",
	"大阪モノレール|国際文化公園都市モノレール線(彩都線)":
		"Osaka Monorail Saito Line",
	"阪急電鉄|千里線": "Hankyu Senri Line",
	"阪急電鉄|今津線": "Hankyu Imazu Line",
	"阪急電鉄|伊丹線": "Hankyu Itami Line",
	"阪急電鉄|甲陽線": "Hankyu Koyo Line",
	"阪急電鉄|神戸高速線": "Hankyu Kobe Kosoku Line",
	"阪神電気鉄道|本線": "Hanshin Main Line",
	"阪神電気鉄道|阪神なんば線": "Hanshin Namba Line",
	"阪神電気鉄道|武庫川線": "Hanshin Mukogawa Line",
	"阪神電気鉄道|神戸高速線": "Hanshin Kobe Kosoku Line",
	"南海電気鉄道|高野線": "Nankai Koya Line",
	"南海電気鉄道|泉北線": "Nankai Semboku Line",
	"南海電気鉄道|鋼索線": "Koyasan Cable Car",
	"南海電気鉄道|加太線": "Nankai Kada Line",
	"南海電気鉄道|和歌山港線": "Nankai Wakayamako Line",
	"南海電気鉄道|多奈川線": "Nankai Tanagawa Line",
	"南海電気鉄道|高師浜線": "Nankai Takashinohama Line",
	"近畿日本鉄道|けいはんな線": "Kintetsu Keihanna Line",
	"近畿日本鉄道|南大阪線": "Kintetsu Minami-Osaka Line",
	"近畿日本鉄道|吉野線": "Kintetsu Yoshino Line",
	"近畿日本鉄道|天理線": "Kintetsu Tenri Line",
	"近畿日本鉄道|生駒線": "Kintetsu Ikoma Line",
	"近畿日本鉄道|田原本線": "Kintetsu Tawaramoto Line",
	"近畿日本鉄道|信貴線": "Kintetsu Shigi Line",
	"近畿日本鉄道|西信貴鋼索線": "Kintetsu Nishi-Shigi Cable Car",
	"近畿日本鉄道|道明寺線": "Kintetsu Domyoji Line",
	"近畿日本鉄道|長野線": "Kintetsu Nagano Line",
	"近畿日本鉄道|御所線": "Kintetsu Gose Line",
	"阪堺電気軌道|阪堺線": "Hankai Line",
	"阪堺電気軌道|上町線": "Hankai Uemachi Line",
	"水間鉄道|水間線": "Mizuma Line",
	"和歌山電鐵|貴志川線": "Kishigawa Line",
	"伊賀鉄道|伊賀線": "Iga Line",
	// ── Kansai: Kobe ─────────────────────────────────────────────────────────
	"神戸市|西神線": "Kobe Subway Seishin-Yamate Line",
	"神戸市|西神延伸線": "Kobe Subway Seishin-Yamate Line",
	"神戸市|山手線": "Kobe Subway Seishin-Yamate Line",
	"神戸市|北神線": "Kobe Subway Hokushin Line",
	"神戸市|海岸線": "Kobe Subway Kaigan Line",
	"神戸新交通|ポートアイランド線": "Port Liner",
	"神戸新交通|六甲アイランド線": "Rokko Liner",
	"山陽電気鉄道|本線": "Sanyo Electric Railway Main Line",
	"神戸電鉄|有馬線": "Shintetsu Arima Line",
	"神戸電鉄|三田線": "Shintetsu Sanda Line",
	"神戸電鉄|公園都市線": "Shintetsu Koen-Toshi Line",
	"神戸電鉄|粟生線": "Shintetsu Ao Line",
	"神戸電鉄|神戸高速線": "Shintetsu Kobe Kosoku Line",
	"能勢電鉄|妙見線": "Nose Myoken Line",
	"能勢電鉄|日生線": "Nose Nissei Line",
	"神戸六甲鉄道|六甲ケーブル線": "Rokko Cable Car",
	"こうべ未来都市機構|摩耶ケーブル線": "Maya Cable Car",
};

/** English operator names (the route step's "agency"). */
export const OPERATOR_NAMES_EN: Readonly<Record<string, string>> = {
	東日本旅客鉄道: "JR East",
	東海旅客鉄道: "JR Central",
	西日本旅客鉄道: "JR West",
	北海道旅客鉄道: "JR Hokkaido",
	四国旅客鉄道: "JR Shikoku",
	九州旅客鉄道: "JR Kyushu",
	東京地下鉄: "Tokyo Metro",
	東京都: "Toei",
	京浜急行電鉄: "Keikyu",
	京王電鉄: "Keio",
	小田急電鉄: "Odakyu",
	小田急箱根: "Odakyu Hakone",
	東急電鉄: "Tokyu",
	西武鉄道: "Seibu",
	東武鉄道: "Tobu",
	京成電鉄: "Keisei",
	相模鉄道: "Sotetsu",
	富士山麓電気鉄道: "Fujikyu",
	東京モノレール: "Tokyo Monorail",
	東京臨海高速鉄道: "Tokyo Waterfront Area Rapid Transit",
	ゆりかもめ: "Yurikamome",
	首都圏新都市鉄道: "Tsukuba Express",
	多摩都市モノレール: "Tama Monorail",
	埼玉高速鉄道: "Saitama Railway",
	北総鉄道: "Hokuso Railway",
	東葉高速鉄道: "Toyo Rapid Railway",
	横浜市: "Yokohama Municipal Subway",
	横浜高速鉄道: "Yokohama Minatomirai Railway",
	江ノ島電鉄: "Enoden",
	湘南モノレール: "Shonan Monorail",
	伊豆急行: "Izukyu",
	伊豆箱根鉄道: "Izuhakone Railway",
	秩父鉄道: "Chichibu Railway",
	名古屋市: "Nagoya Municipal Subway",
	名古屋鉄道: "Meitetsu",
	名古屋臨海高速鉄道: "Aonami Line",
	愛知高速交通: "Linimo",
	愛知環状鉄道: "Aichi Loop Railway",
	近畿日本鉄道: "Kintetsu",
	京阪電気鉄道: "Keihan",
	阪急電鉄: "Hankyu",
	阪神電気鉄道: "Hanshin",
	南海電気鉄道: "Nankai",
	大阪市高速電気軌道: "Osaka Metro",
	北大阪急行電鉄: "Kita-Osaka Kyuko",
	大阪モノレール: "Osaka Monorail",
	京都市: "Kyoto Municipal Subway",
	京福電気鉄道: "Keifuku (Randen)",
	叡山電鉄: "Eizan Railway",
	嵯峨野観光鉄道: "Sagano Scenic Railway",
	神戸市: "Kobe Municipal Subway",
	神戸新交通: "Kobe New Transit",
	山陽電気鉄道: "Sanyo Electric Railway",
	神戸電鉄: "Shintetsu",
	阪堺電気軌道: "Hankai Tramway",
	近江鉄道: "Ohmi Railway",
};

/** The operator's English name, else the N02 (Japanese) one. */
export const operatorEn = (operator: string): string =>
	OPERATOR_NAMES_EN[operator] ?? operator;
