/**
 * Generates `src/data/countries.ts` (SPEC §14.4): `{ ISO2: [lng, lat, zoom] }`
 * for every country in world-atlas 50m (the 110m set lacks Singapore, Hong
 * Kong and other small places a trip visits). The point is the country's
 * `d3-geo` `geoCentroid`; the zoom fits its bounds. A few countries whose
 * geometry pulls the centroid away (overseas territories, Alaska, Svalbard)
 * and the trip's own countries (JP, KR, VN, TW) are set by hand.
 *
 *   N pnpm countries      # rewrites src/data/countries.ts (checked in)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoBounds, geoCentroid } from "d3-geo";
import { feature } from "topojson-client";
import type { GeometryCollection, Topology } from "topojson-specification";

const require = createRequire(import.meta.url);
const atlas = JSON.parse(
	readFileSync(require.resolve("world-atlas/countries-50m.json"), "utf8"),
) as Topology<{ countries: GeometryCollection<{ name: string }> }>;

/** ISO 3166-1 numeric → alpha-2 where Natural Earth's short name doesn't match Intl's English name. */
const NUMERIC_TO_ISO2: Record<string, string> = {
	"028": "AG",
	"036": "AU",
	"070": "BA",
	"086": "IO",
	"090": "SB",
	"092": "VG",
	"104": "MM",
	"132": "CV",
	"136": "KY",
	"140": "CF",
	"178": "CG",
	"180": "CD",
	"184": "CK",
	"214": "DO",
	"226": "GQ",
	"234": "FO",
	"238": "FK",
	"239": "GS",
	"248": "AX",
	"258": "PF",
	"260": "TF",
	"275": "PS",
	"334": "HM",
	"336": "VA",
	"344": "HK",
	"384": "CI",
	"446": "MO",
	"580": "MP",
	"584": "MH",
	"612": "PN",
	"652": "BL",
	"654": "SH",
	"659": "KN",
	"662": "LC",
	"663": "MF",
	"666": "PM",
	"670": "VC",
	"678": "ST",
	"728": "SS",
	"732": "EH",
	"780": "TT",
	"792": "TR",
	"796": "TC",
	"807": "MK",
	"840": "US",
	"850": "VI",
	"876": "WF",
};

/** Hand-set views: [lng, lat, zoom]. */
const OVERRIDES: Record<string, [number, number, number]> = {
	JP: [138.25, 36.2, 4.6],
	KR: [127.85, 36.3, 6.2],
	VN: [106.3, 16.1, 4.9],
	TW: [120.96, 23.7, 6.6],
	US: [-98.6, 39.8, 3.2],
	FR: [2.35, 46.6, 5],
	NO: [10.8, 64.5, 4],
	NL: [5.3, 52.2, 6.5],
	RU: [96, 62, 2],
	NZ: [172.5, -41.5, 4.6],
	CL: [-71.2, -35.7, 3.2],
	GB: [-2.6, 54.2, 4.8],
	ES: [-3.7, 40.2, 5],
	PT: [-8.2, 39.6, 6],
	DK: [10.2, 56.1, 6.2],
};

function zoomFor(bounds: [[number, number], [number, number]]): number {
	const [[w, s], [e, n]] = bounds;
	const dLng = e >= w ? e - w : e + 360 - w;
	const span = Math.max(dLng, (n - s) * 1.6, 0.05);
	return Math.max(
		1.5,
		Math.min(11, Math.round(Math.log2(360 / span) * 10 - 5) / 10),
	);
}

function main(): void {
	const names = new Intl.DisplayNames(["en"], { type: "region" });
	const byName = new Map<string, string>();
	for (let a = 65; a <= 90; a++) {
		for (let b = 65; b <= 90; b++) {
			const code = String.fromCharCode(a, b);
			const name = names.of(code);
			if (name && name !== code) byName.set(name.toLowerCase(), code);
		}
	}
	const fc = feature(atlas, atlas.objects.countries);
	const out = new Map<string, [number, number, number]>();
	const skipped: string[] = [];
	for (const f of fc.features) {
		const id =
			typeof f.id === "string" || typeof f.id === "number"
				? String(f.id).padStart(3, "0")
				: "";
		const iso2 =
			NUMERIC_TO_ISO2[id] ?? byName.get(f.properties.name.toLowerCase());
		if (!iso2) {
			skipped.push(f.properties.name);
			continue;
		}
		const [lng, lat] = geoCentroid(f);
		const view: [number, number, number] = OVERRIDES[iso2] ?? [
			Math.round(lng * 1000) / 1000,
			Math.round(lat * 1000) / 1000,
			zoomFor(geoBounds(f)),
		];
		out.set(iso2, view);
	}
	for (const [iso2, view] of Object.entries(OVERRIDES)) out.set(iso2, view);
	const rows = [...out.entries()].sort(([a], [b]) => a.localeCompare(b));
	const body = rows
		.map(([k, [lng, lat, z]]) => `\t${k}: [${lng}, ${lat}, ${z}],`)
		.join("\n");
	const text = `/**
 * Country views for the map and for country nodes without coordinates
 * (SPEC §14.4): ISO 3166-1 alpha-2 → [lng, lat, zoom].
 *
 * GENERATED by \`pnpm countries\` (scripts/build-countries.ts) from world-atlas
 * 50m with d3-geo; do not edit by hand. ${rows.length} countries.
 */
export const COUNTRY_VIEWS: Readonly<Record<string, readonly [lng: number, lat: number, zoom: number]>> = {
${body}
};

/** The view for an ISO2 code (any case), or null. */
export function countryView(iso2: string | null | undefined): readonly [number, number, number] | null {
	return (iso2 && COUNTRY_VIEWS[iso2.toUpperCase()]) || null;
}
`;
	writeFileSync("src/data/countries.ts", text);
	console.log(
		`[countries] ${rows.length} countries → src/data/countries.ts${skipped.length ? ` (no ISO code: ${skipped.join(", ")})` : ""}`,
	);
}

main();
