/**
 * The Places tab's own test ids (docs/PLACES.md). Import-free, so e2e specs
 * can import it by relative path. Never rename an id.
 */
export const PLACES_TAB_TESTID = {
	tab: "places-tab",
	viewSwitch: "places-view",
	groupBy: "places-group",
	sortBy: "places-sort",
	statusPill: "places-status",
	talkPill: "places-talk",
	search: "places-search",
	progress: "places-progress",
	threshold: "places-threshold",
	// table
	table: "places-table",
	tableScroll: "places-table-scroll",
	row: "places-row",
	groupHeader: "places-group-header",
	splitToggle: "places-split-toggle",
	subgroup: "places-subgroup",
	ratingCell: "places-rating-cell",
	scoreChip: "places-score",
	statusChip: "places-status-chip",
	splitMark: "places-split-mark",
	timeCell: "places-time",
	// board
	board: "places-board",
	card: "places-card",
	// drawer / details
	drawer: "places-drawer",
	pinButton: "places-pin",
	dropButton: "places-drop",
	addToDay: "places-add-to-day",
	myRating: "places-my-rating",
	ratingRow: "places-rating-row",
	timeInput: "places-time-input",
	fits: "places-fits",
	nearby: "places-nearby",
	// map
	map: "places-map",
	mapPin: "places-map-pin",
	mapList: "places-map-list",
	mapRow: "places-map-row",
	mapBack: "places-map-back",
	mapDetails: "places-map-details",
	// rate feed
	feed: "places-feed",
	feedCard: "places-feed-card",
	feedButton: "places-feed-button",
	feedReveal: "places-feed-reveal",
	feedTag: "places-feed-tag",
	feedTime: "places-feed-time",
	/** D07: "The group", after you rate. */
	feedGroup: "places-feed-group",
	feedPos: "places-feed-pos",
	rowPick: "places-row-pick",
	pickAll: "places-pick-all",
	selectionBar: "places-selection-bar",
	decideWaiting: "places-decide-waiting",
	selectionDay: "places-selection-day",
	selectionRate: "places-selection-rate",
	selectionDrop: "places-selection-drop",
	feedPrev: "places-feed-prev",
	feedNext: "places-feed-next",
	feedLinks: "places-feed-links",
	feedPeek: "places-feed-peek",
	feedLeft: "places-feed-left",
	feedRun: "places-feed-run",
	feedSkipped: "places-feed-skipped",
	feedMilestone: "places-feed-milestone",
	feedEnd: "places-feed-end",
	feedOrder: "places-feed-order",
	feedInvite: "places-feed-invite",
	feedReview: "places-feed-review",
	feedTalk: "places-feed-talk",
	/** A narrow card's note line, and its open notes box. */
	feedStage: "places-feed-stage",
	feedBar: "places-feed-bar",
	feedInfo: "places-feed-info",
	// the views: all places, rate, decide (One Yonder D06)
	steps: "places-steps",
	/** One Yonder D08: the Decide view, its columns and cards. */
	decide: "places-decide",
	decideColumn: "places-decide-column",
	decideCard: "places-decide-card",
	decideKeep: "places-decide-keep",
	decideDrop: "places-decide-drop",
	decideBack: "places-decide-back",
	/** "Mark Kyoto decided", "Decided · Undo", "Decided with Japan", split but decided. */
	decideMark: "places-decide-mark",
	decideDecided: "places-decide-decided",
	decideUndo: "places-decide-undo",
	decideDecidedWith: "places-decide-decided-with",
	decideSettled: "places-decide-settled",
	step: "places-step",
	stepCount: "places-step-count",
	stepDot: "places-step-dot",
	addPlace: "places-add-place",
	flowEmpty: "places-flow-empty",
	// how long in each city lives in the Plan: `plan/day-split/testids.ts`
	ratePill: "places-rate-pill",
	nextStep: "places-next-step",
} as const;
