/**
 * The Places tab's own test ids (docs/PLACES.md). Import-free, so e2e specs
 * can import it by relative path. Never rename an id.
 */
export const PLACES_TAB_TESTID = {
	tab: "places-tab",
	viewSwitch: "places-view",
	groupBy: "places-group",
	sortBy: "places-sort",
	statusPill: "places-status",
	talkPill: "places-talk",
	search: "places-search",
	wide: "places-wide",
	progress: "places-progress",
	threshold: "places-threshold",
	// table
	table: "places-table",
	tableScroll: "places-table-scroll",
	row: "places-row",
	groupHeader: "places-group-header",
	splitToggle: "places-split-toggle",
	subgroup: "places-subgroup",
	ratingCell: "places-rating-cell",
	scoreChip: "places-score",
	statusChip: "places-status-chip",
	splitMark: "places-split-mark",
	timeCell: "places-time",
	// board
	board: "places-board",
	card: "places-card",
	// drawer / details
	drawer: "places-drawer",
	drawerClose: "places-drawer-close",
	pinButton: "places-pin",
	dropButton: "places-drop",
	addToDay: "places-add-to-day",
	myRating: "places-my-rating",
	ratingRow: "places-rating-row",
	timeInput: "places-time-input",
	fits: "places-fits",
	nearby: "places-nearby",
	// map
	map: "places-map",
	mapPin: "places-map-pin",
	mapList: "places-map-list",
	mapRow: "places-map-row",
	mapBack: "places-map-back",
	mapDetails: "places-map-details",
	// rate feed
	feed: "places-feed",
	feedCard: "places-feed-card",
	feedButton: "places-feed-button",
	feedReveal: "places-feed-reveal",
	feedTag: "places-feed-tag",
	feedPeek: "places-feed-peek",
	feedLeft: "places-feed-left",
	feedRun: "places-feed-run",
	feedSkipped: "places-feed-skipped",
	feedMilestone: "places-feed-milestone",
	feedEnd: "places-feed-end",
	feedOrder: "places-feed-order",
	feedInvite: "places-feed-invite",
	feedShortlist: "places-feed-shortlist",
} as const;
