/**
 * WP-Transit's own test ids (CONTRACTS §1 rule 8). Import-free. The shared
 * ones (`leg`, `leg-mode`, `leg-overview`, `edge-overview`,
 * `add-flight-dialog`) stay in `src/lib/testids.ts`.
 */
export const TRANSIT_TESTID = {
	modeOption: "leg-mode-option", // [data-mode]
	travellers: "leg-travellers",
	legMenu: "leg-menu",
	walkPanel: "walk-panel",
	walkMinutes: "walk-minutes",
	walkSource: "walk-source",
	walkReset: "walk-reset",
	transitPanel: "transit-panel",
	transitTime: "transit-time",
	transitUseFastest: "transit-use-fastest",
	transitReset: "transit-reset",
	transitDoorToDoor: "transit-door-to-door",
	transitDeparting: "transit-departing",
	transitRefresh: "transit-refresh",
	transitOption: "transit-option", // [data-source] [data-chosen] [data-fastest]
	transitOptionChoose: "transit-option-choose",
	transitOptionEdit: "transit-option-edit",
	transitOptionDelete: "transit-option-delete",
	transitOptionLock: "transit-option-lock",
	fastestBadge: "transit-fastest",
	japanNote: "japan-transit-note",
	googleMapsLink: "open-in-google-maps",
	railAttribution: "rail-attribution",
	transitWarning: "transit-warning",
	transitError: "transit-error",
	noProvider: "transit-no-provider",
	customRouteAdd: "custom-route-add",
	customRoute: "custom-route",
	customRouteLabel: "custom-route-label",
	customRouteDurationOnly: "custom-route-duration-only",
	customRouteMinutes: "custom-route-minutes",
	customRouteStep: "custom-route-step",
	customRouteStepMode: "custom-route-step-mode",
	customRouteStepLine: "custom-route-step-line",
	customRouteStepFrom: "custom-route-step-from",
	customRouteStepTo: "custom-route-step-to",
	customRouteStepDepart: "custom-route-step-depart",
	customRouteStepMinutes: "custom-route-step-minutes",
	customRouteAddStep: "custom-route-add-step",
	customRouteReserved: "custom-route-reserved",
	customRouteDepartDate: "custom-route-depart-date",
	customRouteDepartTime: "custom-route-depart-time",
	customRouteArriveDate: "custom-route-arrive-date",
	customRouteArriveTime: "custom-route-arrive-time",
	customRouteAccess: "custom-route-access",
	customRouteEgress: "custom-route-egress",
	customRouteBooking: "custom-route-booking",
	bookingRef: "booking-ref",
	bookingTrain: "booking-train",
	bookingClass: "booking-class",
	bookingCar: "booking-car",
	bookingSeat: "booking-seat", // [data-member]
	customRouteSave: "custom-route-save",
	customRouteCancel: "custom-route-cancel",
	stationSuggestion: "station-suggestion",
	chosenBooking: "chosen-booking",
	flightForm: "flight-form",
	flightSegment: "flight-segment",
	flightAirline: "flight-airline",
	flightNumber: "flight-number",
	flightFrom: "flight-from",
	flightTo: "flight-to",
	flightDepDate: "flight-dep-date",
	flightDepTime: "flight-dep-time",
	flightArrDate: "flight-arr-date",
	flightArrTime: "flight-arr-time",
	flightDuration: "flight-duration",
	flightFromTerminal: "flight-from-terminal",
	flightToTerminal: "flight-to-terminal",
	flightFromGate: "flight-from-gate",
	flightToGate: "flight-to-gate",
	flightCabin: "flight-cabin",
	flightSeat: "flight-seat", // [data-member]
	flightRef: "flight-ref",
	flightBaggage: "flight-baggage",
	flightAircraft: "flight-aircraft",
	flightCostAmount: "flight-cost-amount",
	flightCostCurrency: "flight-cost-currency",
	flightPointsProgram: "flight-points-program",
	flightPointsAmount: "flight-points-amount",
	flightFeesAmount: "flight-fees-amount",
	flightAddConnection: "flight-add-connection",
	flightRemoveSegment: "flight-remove-segment",
	flightSave: "flight-save",
	flightError: "flight-error", // [data-field]
	flightSummary: "flight-summary",
	flightEdit: "flight-edit",
	/** FB-18: the one-line "NH 9 · JFK → HND · ~14h 5m est. · times TBD". */
	flightLine: "flight-line",
	flightDepClock: "flight-dep-clock",
	flightDstNote: "flight-dst-note",
	/** QA TZ-07: the first / second of a repeated local time ("01:30 EDT" / "01:30 EST"). */
	flightFold: "flight-fold",
	addPerson: "transit-add-person",
	flightConflict: "flight-conflict",
	airportOption: "airport-option",
	airlineOption: "airline-option",
	otherPanel: "other-panel",
	otherKind: "other-kind", // [data-kind]
	otherMinutes: "other-minutes",
	otherLabel: "other-label",
	overnight: "leg-overnight",
	overnightAddTransit: "overnight-add-transit",
	overnightSetStay: "overnight-set-stay",
	edgeLeg: "edge-leg",
	masked: "booking-masked",
} as const;

export type TransitTestId =
	(typeof TRANSIT_TESTID)[keyof typeof TRANSIT_TESTID];
