/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as authJoinRouteImport } from './routes/(auth)/join'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authWelcomeRouteImport } from './routes/(auth)/welcome'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedShareRouteImport } from './routes/_authed/share'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DevFixtureRouteImport } from './routes/dev/fixture'
import { Route as TTripRouteImport } from './routes/t/$trip'
import { Route as authSTokenRouteImport } from './routes/(auth)/s/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAvatarUserIdRouteImport } from './routes/api/avatar/$userId'
import { Route as ApiTestFixtureRouteImport } from './routes/api/test/fixture'
import { Route as DevFixtureIndexRouteImport } from './routes/dev/fixture/index'
import { Route as DevFixtureSplatRouteImport } from './routes/dev/fixture/$'
import { Route as MediaIdVariantRouteImport } from './routes/media/$id/$variant'
import { Route as TTripIndexRouteImport } from './routes/t/$trip/index'
import { Route as TTripSplatRouteImport } from './routes/t/$trip/$'
import { Route as TTripRateRouteImport } from './routes/t/$trip_.rate'
import { Route as TTripShareCardDotpngRouteImport } from './routes/t/$trip_.share-card[.]png'
import { Route as ApiPlacesPhotoSplatRouteImport } from './routes/api/places/photo/$'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const authJoinRoute = authJoinRouteImport.update({
  id: '/(auth)/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authWelcomeRoute = authWelcomeRouteImport.update({
  id: '/(auth)/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShareRoute = AuthedShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFixtureRoute = DevFixtureRouteImport.update({
  id: '/dev/fixture',
  path: '/dev/fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const TTripRoute = TTripRouteImport.update({
  id: '/t/$trip',
  path: '/t/$trip',
  getParentRoute: () => rootRouteImport,
} as any)
const authSTokenRoute = authSTokenRouteImport.update({
  id: '/(auth)/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarUserIdRoute = ApiAvatarUserIdRouteImport.update({
  id: '/api/avatar/$userId',
  path: '/api/avatar/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestFixtureRoute = ApiTestFixtureRouteImport.update({
  id: '/api/test/fixture',
  path: '/api/test/fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFixtureIndexRoute = DevFixtureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevFixtureRoute,
} as any)
const DevFixtureSplatRoute = DevFixtureSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DevFixtureRoute,
} as any)
const MediaIdVariantRoute = MediaIdVariantRouteImport.update({
  id: '/media/$id/$variant',
  path: '/media/$id/$variant',
  getParentRoute: () => rootRouteImport,
} as any)
const TTripIndexRoute = TTripIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTripRoute,
} as any)
const TTripSplatRoute = TTripSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => TTripRoute,
} as any)
const TTripRateRoute = TTripRateRouteImport.update({
  id: '/t/$trip_/rate',
  path: '/t/$trip/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const TTripShareCardDotpngRoute = TTripShareCardDotpngRouteImport.update({
  id: '/t/$trip_/share-card.png',
  path: '/t/$trip/share-card.png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesPhotoSplatRoute = ApiPlacesPhotoSplatRouteImport.update({
  id: '/api/places/photo/$',
  path: '/api/places/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/join': typeof authJoinRoute
  '/login': typeof authLoginRoute
  '/welcome': typeof authWelcomeRoute
  '/share': typeof AuthedShareRoute
  '/api/health': typeof ApiHealthRoute
  '/dev/fixture': typeof DevFixtureRouteWithChildren
  '/t/$trip': typeof TTripRouteWithChildren
  '/s/$token': typeof authSTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
  '/api/test/fixture': typeof ApiTestFixtureRoute
  '/dev/fixture/$': typeof DevFixtureSplatRoute
  '/media/$id/$variant': typeof MediaIdVariantRoute
  '/t/$trip/$': typeof TTripSplatRoute
  '/t/$trip/rate': typeof TTripRateRoute
  '/t/$trip/share-card.png': typeof TTripShareCardDotpngRoute
  '/dev/fixture/': typeof DevFixtureIndexRoute
  '/t/$trip/': typeof TTripIndexRoute
  '/api/places/photo/$': typeof ApiPlacesPhotoSplatRoute
}
export interface FileRoutesByTo {
  '/join': typeof authJoinRoute
  '/login': typeof authLoginRoute
  '/welcome': typeof authWelcomeRoute
  '/share': typeof AuthedShareRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/s/$token': typeof authSTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
  '/api/test/fixture': typeof ApiTestFixtureRoute
  '/dev/fixture/$': typeof DevFixtureSplatRoute
  '/media/$id/$variant': typeof MediaIdVariantRoute
  '/t/$trip/$': typeof TTripSplatRoute
  '/t/$trip/rate': typeof TTripRateRoute
  '/t/$trip/share-card.png': typeof TTripShareCardDotpngRoute
  '/dev/fixture': typeof DevFixtureIndexRoute
  '/t/$trip': typeof TTripIndexRoute
  '/api/places/photo/$': typeof ApiPlacesPhotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/(auth)/join': typeof authJoinRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/welcome': typeof authWelcomeRoute
  '/_authed/share': typeof AuthedShareRoute
  '/api/health': typeof ApiHealthRoute
  '/dev/fixture': typeof DevFixtureRouteWithChildren
  '/t/$trip': typeof TTripRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/(auth)/s/$token': typeof authSTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/avatar/$userId': typeof ApiAvatarUserIdRoute
  '/api/test/fixture': typeof ApiTestFixtureRoute
  '/dev/fixture/$': typeof DevFixtureSplatRoute
  '/media/$id/$variant': typeof MediaIdVariantRoute
  '/t/$trip/$': typeof TTripSplatRoute
  '/t/$trip_/rate': typeof TTripRateRoute
  '/t/$trip_/share-card.png': typeof TTripShareCardDotpngRoute
  '/dev/fixture/': typeof DevFixtureIndexRoute
  '/t/$trip/': typeof TTripIndexRoute
  '/api/places/photo/$': typeof ApiPlacesPhotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/welcome'
    | '/share'
    | '/api/health'
    | '/dev/fixture'
    | '/t/$trip'
    | '/s/$token'
    | '/api/auth/$'
    | '/api/avatar/$userId'
    | '/api/test/fixture'
    | '/dev/fixture/$'
    | '/media/$id/$variant'
    | '/t/$trip/$'
    | '/t/$trip/rate'
    | '/t/$trip/share-card.png'
    | '/dev/fixture/'
    | '/t/$trip/'
    | '/api/places/photo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join'
    | '/login'
    | '/welcome'
    | '/share'
    | '/api/health'
    | '/'
    | '/s/$token'
    | '/api/auth/$'
    | '/api/avatar/$userId'
    | '/api/test/fixture'
    | '/dev/fixture/$'
    | '/media/$id/$variant'
    | '/t/$trip/$'
    | '/t/$trip/rate'
    | '/t/$trip/share-card.png'
    | '/dev/fixture'
    | '/t/$trip'
    | '/api/places/photo/$'
  id:
    | '__root__'
    | '/_authed'
    | '/(auth)/join'
    | '/(auth)/login'
    | '/(auth)/welcome'
    | '/_authed/share'
    | '/api/health'
    | '/dev/fixture'
    | '/t/$trip'
    | '/_authed/'
    | '/(auth)/s/$token'
    | '/api/auth/$'
    | '/api/avatar/$userId'
    | '/api/test/fixture'
    | '/dev/fixture/$'
    | '/media/$id/$variant'
    | '/t/$trip/$'
    | '/t/$trip_/rate'
    | '/t/$trip_/share-card.png'
    | '/dev/fixture/'
    | '/t/$trip/'
    | '/api/places/photo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  authJoinRoute: typeof authJoinRoute
  authLoginRoute: typeof authLoginRoute
  authWelcomeRoute: typeof authWelcomeRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DevFixtureRoute: typeof DevFixtureRouteWithChildren
  TTripRoute: typeof TTripRouteWithChildren
  authSTokenRoute: typeof authSTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAvatarUserIdRoute: typeof ApiAvatarUserIdRoute
  ApiTestFixtureRoute: typeof ApiTestFixtureRoute
  MediaIdVariantRoute: typeof MediaIdVariantRoute
  TTripRateRoute: typeof TTripRateRoute
  TTripShareCardDotpngRoute: typeof TTripShareCardDotpngRoute
  ApiPlacesPhotoSplatRoute: typeof ApiPlacesPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/join': {
      id: '/(auth)/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof authJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/welcome': {
      id: '/(auth)/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof authWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/share': {
      id: '/_authed/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof AuthedShareRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/fixture': {
      id: '/dev/fixture'
      path: '/dev/fixture'
      fullPath: '/dev/fixture'
      preLoaderRoute: typeof DevFixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$trip': {
      id: '/t/$trip'
      path: '/t/$trip'
      fullPath: '/t/$trip'
      preLoaderRoute: typeof TTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/s/$token': {
      id: '/(auth)/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof authSTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/$userId': {
      id: '/api/avatar/$userId'
      path: '/api/avatar/$userId'
      fullPath: '/api/avatar/$userId'
      preLoaderRoute: typeof ApiAvatarUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/fixture': {
      id: '/api/test/fixture'
      path: '/api/test/fixture'
      fullPath: '/api/test/fixture'
      preLoaderRoute: typeof ApiTestFixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/fixture/': {
      id: '/dev/fixture/'
      path: '/'
      fullPath: '/dev/fixture/'
      preLoaderRoute: typeof DevFixtureIndexRouteImport
      parentRoute: typeof DevFixtureRoute
    }
    '/dev/fixture/$': {
      id: '/dev/fixture/$'
      path: '/$'
      fullPath: '/dev/fixture/$'
      preLoaderRoute: typeof DevFixtureSplatRouteImport
      parentRoute: typeof DevFixtureRoute
    }
    '/media/$id/$variant': {
      id: '/media/$id/$variant'
      path: '/media/$id/$variant'
      fullPath: '/media/$id/$variant'
      preLoaderRoute: typeof MediaIdVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$trip/': {
      id: '/t/$trip/'
      path: '/'
      fullPath: '/t/$trip/'
      preLoaderRoute: typeof TTripIndexRouteImport
      parentRoute: typeof TTripRoute
    }
    '/t/$trip/$': {
      id: '/t/$trip/$'
      path: '/$'
      fullPath: '/t/$trip/$'
      preLoaderRoute: typeof TTripSplatRouteImport
      parentRoute: typeof TTripRoute
    }
    '/t/$trip_/rate': {
      id: '/t/$trip_/rate'
      path: '/t/$trip/rate'
      fullPath: '/t/$trip/rate'
      preLoaderRoute: typeof TTripRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$trip_/share-card.png': {
      id: '/t/$trip_/share-card.png'
      path: '/t/$trip/share-card.png'
      fullPath: '/t/$trip/share-card.png'
      preLoaderRoute: typeof TTripShareCardDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/photo/$': {
      id: '/api/places/photo/$'
      path: '/api/places/photo/$'
      fullPath: '/api/places/photo/$'
      preLoaderRoute: typeof ApiPlacesPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedShareRoute: typeof AuthedShareRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedShareRoute: AuthedShareRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface DevFixtureRouteChildren {
  DevFixtureSplatRoute: typeof DevFixtureSplatRoute
  DevFixtureIndexRoute: typeof DevFixtureIndexRoute
}

const DevFixtureRouteChildren: DevFixtureRouteChildren = {
  DevFixtureSplatRoute: DevFixtureSplatRoute,
  DevFixtureIndexRoute: DevFixtureIndexRoute,
}

const DevFixtureRouteWithChildren = DevFixtureRoute._addFileChildren(
  DevFixtureRouteChildren,
)

interface TTripRouteChildren {
  TTripSplatRoute: typeof TTripSplatRoute
  TTripIndexRoute: typeof TTripIndexRoute
}

const TTripRouteChildren: TTripRouteChildren = {
  TTripSplatRoute: TTripSplatRoute,
  TTripIndexRoute: TTripIndexRoute,
}

const TTripRouteWithChildren = TTripRoute._addFileChildren(TTripRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  authJoinRoute: authJoinRoute,
  authLoginRoute: authLoginRoute,
  authWelcomeRoute: authWelcomeRoute,
  ApiHealthRoute: ApiHealthRoute,
  DevFixtureRoute: DevFixtureRouteWithChildren,
  TTripRoute: TTripRouteWithChildren,
  authSTokenRoute: authSTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAvatarUserIdRoute: ApiAvatarUserIdRoute,
  ApiTestFixtureRoute: ApiTestFixtureRoute,
  MediaIdVariantRoute: MediaIdVariantRoute,
  TTripRateRoute: TTripRateRoute,
  TTripShareCardDotpngRoute: TTripShareCardDotpngRoute,
  ApiPlacesPhotoSplatRoute: ApiPlacesPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
